apiVersion: v1
kind: Secret
metadata:
  name: anra-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "anra.labels" . | nindent 4 }}
type: Opaque
stringData:
  influxdb-token: {{ .Values.secrets.influxdbToken | default "anra-default-token" | quote }}
  {{- if .Values.secrets.bmcPassword }}
  bmc-password: {{ .Values.secrets.bmcPassword | quote }}
  {{- end }}
