apiVersion: v1
kind: Service
metadata:
  name: anra
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "anra.labels" . | nindent 4 }}
  {{- if eq .Values.webui.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  {{- end }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.port }}
      targetPort: http
      {{- if eq .Values.webui.service.type "NodePort" }}
      nodePort: {{ .Values.webui.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "anra.selectorLabels" . | nindent 4 }}
