[agent]
  interval = "15s"
  flush_interval = "15s"
[[inputs.execd]]
  command = ["python3", "/etc/srs/core_collector.py"]
  signal = "none"
  data_format = "json"
  name_override = "core_network"
[[outputs.influxdb_v2]]
  urls = ["http://influxdb.anra.svc.cluster.local:8086"]
  token = "$INFLUX_TOKEN"
  organization = "srs"
  bucket = "srsran"
