[agent]
  interval = "1s"
  flush_interval = "5s"

[[inputs.execd]]
  command = ["python3", "/etc/telegraf/ws_adapter.py"]
  signal = "none"
  restart_delay = "5s"
  data_format = "influx"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb.anra.svc:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "srs"
  bucket = "srsran"
