[agent]
  interval = "30s"
  flush_interval = "30s"

[[inputs.redfish]]
  address = "${BMC_ADDRESS}"
  username = "${BMC_USER}"
  password = "${BMC_PASS}"
  computer_system_id = "System.Embedded.1"

[[inputs.internal]]
  collect_memstats = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb.anra.svc:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "srs"
  bucket = "srsran"
