apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anra.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "anra.labels" . | nindent 4 }}
data:
  agent-config.yaml: |
    {{- include "anra-common.agent-config" . | nindent 4 }}
