apiVersion: v1
kind: Service
metadata:
  name: {{ include "anra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "anra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webui.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.webui.service.port | default 8080 }}
      targetPort: {{ .Values.webui.port | default 8080 }}
      protocol: TCP
      {{- if and (eq (.Values.webui.service.type | default "ClusterIP") "NodePort") .Values.webui.service.nodePort }}
      nodePort: {{ .Values.webui.service.nodePort }}
      {{- end }}
  selector:
    {{- include "anra.selectorLabels" . | nindent 4 }}
