apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open5gs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 833542146025.dkr.ecr.us-west-1.amazonaws.com
    chart: helm/open5gs
    targetRevision: 2.3.4
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: open5gs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
