apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: srsran
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/aws-samples/sample-sop-agent-for-telco.git
    targetRevision: main
    path: gitops/base/srsran
  destination:
    server: https://kubernetes.default.svc
    namespace: srsran
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
