apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anda.fullname" . }}-validation-rules
  labels:
    {{- include "anda.labels" . | nindent 4 }}
data:
  validation.yaml: |
    preflight:
      enabled: {{ .Values.validation.preflight.enabled }}
      checks:
        {{- toYaml .Values.validation.preflight.checks | nindent 8 }}
    postDeploy:
      enabled: {{ .Values.validation.postDeploy.enabled }}
      checks:
        {{- toYaml .Values.validation.postDeploy.checks | nindent 8 }}
